# Gen5 Clean Ice Physics + Velocity - Frodo
# Uses phys64_s075 dataset (same as multi-class)
training_opts:
  dataset_name: bibek_w512_o64_f1_v2_phys64_s075_velocity
  run_name: ci_physics_velocity_gen5

loader_opts:
  physics_channels: true
  velocity_channels: true