# Only output dataset name - all paths come from servers.yaml
output_name: "bibek_w512_o64_f1_velocity"

# Preprocessing parameters
window_size: [512, 512]
overlap: 64
filter: 0.1
test: 0.2
val: 0.1
add_velocity: True # Enable ITS_LIVE velocity features (4 bands)
add_ndvi: True
add_ndwi: True
add_ndsi: True
add_hsv: True
physics_res: None # 64 or int or "full" or None
physics_scale: 1 # float between (0, 1]
