# Server configurations for distributed experiments

desktop:
  hostname: localhost
  ssh_host: null
  code_path: /home/devj/local-debian/Python-Glacier-Mapping-by-Segmentation
  output_path: /home/devj/local-debian/Python-Glacier-Mapping-by-Segmentation/output
  # Preprocessing input directories
  image_dir: /home/devj/local-debian/datasets/HKH_raw/Landsat7_2005
  dem_dir: /home/devj/local-debian/datasets/HKH_raw/DEM
  labels_dir: /home/devj/local-debian/datasets/HKH_raw/labels_fixed
  # Preprocessing output directory
  processed_data_path: /home/devj/local-debian/datasets/HKH

bilbo:
  hostname: bilbo
  ssh_host: jperez@bilbo
  code_path: /home/jperez/Python-Glacier-Mapping-by-Segmentation
  output_path: /data/jperez/output
  # Preprocessing input directories
  image_dir: /data/jperez/datasets/HKH_raw/Landsat7_2005
  dem_dir: /data/jperez/datasets/HKH_raw/DEM
  labels_dir: /data/jperez/datasets/HKH_raw/labels_fixed
  # Preprocessing output directory
  processed_data_path: /home/jperez/datasets/HKH

frodo:
  hostname: frodo
  ssh_host: jperez@frodo
  code_path: /home/jperez/Python-Glacier-Mapping-by-Segmentation
  output_path: /data/jperez/output
  # Preprocessing input directories
  image_dir: /home/jperez/datasets/HKH_raw/Landsat7_2005
  dem_dir: /home/jperez/datasets/HKH_raw/DEM
  labels_dir: /home/jperez/datasets/HKH_raw/labels_fixed
  # Preprocessing output directory
  processed_data_path: /home/jperez/datasets/HKH
