# Gen4 Debris Ice Physics Only - Frodo
# Uses phys64_s1 dataset (same as combined)
training_opts:
  dataset_name: bibek_w512_o64_f1_v2_phys64_s1_velocity
  run_name: dci_physics_gen4

loader_opts:
  physics_channels: true
  velocity_channels: false