# Desktop Clean Ice Velocity Gen3
# Inherits from configs/train.yaml + configs/servers.yaml[desktop] + configs/tasks/clean_ice.yaml

training_opts:
  dataset_name: bibek_w512_o64_f1_velocity
  run_name: desktop_clean_ice_velocity_gen3

loader_opts:
  velocity_channels: true