# Gen5 Debris Ice Physics + Velocity - Bilbo
# Uses phys64_s1 dataset
training_opts:
  dataset_name: bibek_w512_o64_f1_v2_phys64_s1_velocity
  run_name: dci_physics_velocity_gen5

loader_opts:
  physics_channels: true
  velocity_channels: true