# Gen4 Multi-class Physics + Velocity - Bilbo
# Uses phys64_s075 dataset (same as clean ice)
training_opts:
  dataset_name: bibek_w512_o64_f1_v2_phys64_s075_velocity
  run_name: multi_physics_velocity_gen4

loader_opts:
  physics_channels: true
  velocity_channels: true